% Test script to run a single LoKI-B simulation
% This verifies that the setup is working correctly

clear all; close all; clc;

fprintf('=== Testing Single LoKI-B Simulation ===\n\n');

% Test with a simple configuration
fprintf('Running test simulation with N=100, delta_u=1e-3 eV...\n');

% Create a simple test input file
test_input = sprintf(['%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%\n', ...
                     '%%   TEST SIMULATION          %%\n', ...
                     '%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%\n\n', ...
                     '%% --- configuration of the working conditions ---\n', ...
                     'workingConditions:\n', ...
                     '  reducedField: 10                      %% in Td\n', ...
                     '  electronTemperature: linspace(0.03, 5, 100) %% in eV\n', ...
                     '  excitationFrequency: 0                      %% in Hz\n', ...
                     '  gasPressure: 133.32                         %% in Pa\n', ...
                     '  gasTemperature: 300                         %% in K\n', ...
                     '  wallTemperature: 130                        %% in K\n', ...
                     '  extTemperature: 300                         %% in K\n', ...
                     '  surfaceSiteDensity: 1e19                    %% in m-2\n', ...
                     '  electronDensity: 1e19                       %% in m-3\n', ...
                     '  chamberLength: 1.0                          %% in m\n', ...
                     '  chamberRadius: 1.0                          %% in m\n\n', ...
                     '%% --- configuration of the electron kinetics ---\n', ...
                     'electronKinetics:\n', ...
                     '  isOn: true                           %% true or false\n', ...
                     '  eedfType: boltzmann                  %% boltzmann or prescribedEedf\n', ...
                     '  ionizationOperatorType: conservative %% conservative, oneTakesAll, equalSharing or usingSDCS\n', ...
                     '  growthModelType: temporal            %% temporal or spatial\n', ...
                     '  includeEECollisions: true            %% true or false\n', ...
                     '  LXCatFiles:                          %% cross section files\n', ...
                     '    - Hydrogen/H2_elastic_LXCat.txt\n', ...
                     '    - Hydrogen/H2_LXCat.txt\n', ...
                     '  CARgases:                           %% gases for which CAR is activated\n', ...
                     '    - H2\n', ...
                     '  gasProperties:                       %% properties of the gases (S.I. Units)\n', ...
                     '    mass: Databases/masses.txt\n', ...
                     '    fraction:\n', ...
                     '      - H2 = 1\n', ...
                     '    harmonicFrequency: Databases/harmonicFrequencies.txt\n', ...
                     '    anharmonicFrequency: Databases/anharmonicFrequencies.txt\n', ...
                     '    rotationalConstant: Databases/rotationalConstants.txt\n', ...
                     '    electricQuadrupoleMoment: Databases/quadrupoleMoment.txt\n', ...
                     '    OPBParameter: Databases/OPBParameter.txt\n', ...
                     '  stateProperties:                     %% properties of the states\n', ...
                     '    population:\n', ...
                     '      - H2(X) = 1.0\n', ...
                     '  numerics:                            %% configuration of numerical details\n', ...
                     '    energyGrid:                        %% properties of the energy grid (in eV)\n', ...
                     '      variableGrid: true              %% if true, sets a geometric progression\n', ...
                     '      firstEnergyStep: 1e-3          %% delta u = 1e-3 eV\n', ...
                     '      maxEnergy: 10                     %% max energy\n', ...
                     '      cellNumber: 100                 %% N = 100\n', ...
                     '    maxPowerBalanceRelError: 1e-9      %% threshold for power balance warning\n', ...
                     '    nonLinearRoutines:\n', ...
                     '      algorithm: mixingDirectSolutions %% mixingDirectSolutions or temporalIntegration\n', ...
                     '      mixingParameter: 0.7             %% mixingDirectSolutions mixing parameter\n', ...
                     '      maxEedfRelError: 1e-9            %% maximum rel. variation for EEDF\n', ...
                     '          \n', ...
                     '%% --- configuration of the graphical user interface ---\n', ...
                     'gui: \n', ...
                     '  isOn: false\n', ...
                     '  refreshFrequency: 1\n\n', ...
                     '%% ---  configuration of the output files ---\n', ...
                     'output: \n', ...
                     '  isOn: true\n', ...
                     '  dataFormat: txt %% txt or hdf5 or hdf5+txt\n', ...
                     '  folder: test_simulation\n', ...
                     '  dataSets:\n', ...
                     '    - log\n', ...
                     '    - eedf\n', ...
                     '    - swarmParameters\n', ...
                     '    - rateCoefficients\n', ...
                     '    - powerBalance\n', ...
                     '    - lookUpTable\n']);

% Write test input file
fid = fopen('Input/test_simulation.in', 'w');
fprintf(fid, '%s', test_input);
fclose(fid);

    % Run the simulation
    try
        tic;
        lokibcl('Input/test_simulation.in');
        sim_time = toc;
    
    fprintf('Simulation completed successfully in %.2f seconds!\n', sim_time);
    
    % Check if output files were created
    if exist('Output/test_simulation', 'dir')
        fprintf('Output files created successfully.\n');
        
        % List output files
        output_files = dir('Output/test_simulation/*.txt');
        fprintf('Output files:\n');
        for i = 1:length(output_files)
            fprintf('  %s\n', output_files(i).name);
        end
    else
        fprintf('Warning: No output directory found.\n');
    end
    
catch ME
    fprintf('ERROR: Simulation failed with message: %s\n', ME.message);
    fprintf('Stack trace:\n');
    for i = 1:length(ME.stack)
        fprintf('  %s (line %d)\n', ME.stack(i).name, ME.stack(i).line);
    end
end

% Clean up test file
if exist('Input/test_simulation.in', 'file')
    delete('Input/test_simulation.in');
end

fprintf('\n=== Test completed ===\n'); 